#!/usr/bin/env python3
from os.path import exists
from os import system
from subprocess import run
from sys import exit
import argparse

def createTargetFile():
    with open(TARGET_FILE, "w") as f:
        f.write("# explicitly installed packages:\n\n")
        f.write(run(["pacman", "-Qeq"], capture_output=True, text=True, check=True).stdout)

        f.write("\n\n# non-explicitly installed packages:\n\n")
        f.write(run(["pacman", "-Qdq"], capture_output=True, text=True, check=True).stdout)



if exists("/usr/bin/yay"):
    cmd = ["yay"]
elif exists("/usr/bin/paru"):
    cmd = ["paru"]
elif exists("/usr/bin/pikaur"):
    cmd = ["pikaur"]
else:
    cmd = ["sudo", "pacman"]

parser = argparse.ArgumentParser(
    prog='arch_declarative',
    description='Declarative pacman package list',
    # argument_default=[],
)

TARGET_FILE = "desired_arch_packages"

parser.add_argument('-I', '--install-interactive', action='store_true', help='Fuzzy search and install packages, <TAB> selects multiple')
parser.add_argument('-R', '--remove-interactive', action='store_true', help='Fuzzy search and remove packages, <TAB> selects multiple')

arguments = parser.parse_args()

if not exists(TARGET_FILE):
    createTargetFile()

    if not arguments.install_interactive and not arguments.remove_interactive:
        print(f"Created '{TARGET_FILE}'. Edit it to define your target packages, then rerun.")
        exit(0)

if arguments.install_interactive:
    system(f"{cmd[-1]} -Slq | fzf --multi --preview '{cmd[-1]} -Si {{1}}' | cat >> " + TARGET_FILE)

if arguments.remove_interactive:
    system("cat " + TARGET_FILE + " | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns && rm desired_arch_packages")
    createTargetFile()
    exit(0)

with open(TARGET_FILE) as f:
    desired_packages = {
        line.strip() for line in f 
        if line.strip() and not line.strip().startswith("#")
    }

result = run([cmd[-1], "-Qq"], capture_output=True, text=True, check=True)
installed_packages = set(result.stdout.splitlines())

to_install = sorted(desired_packages - installed_packages)
to_remove = sorted(installed_packages - desired_packages)

if to_install:
    cmd.extend(["-S", "--needed"])
    print(f"Installing: {' '.join(to_install)}")
    cmd.extend(to_install)
    system(" ".join(cmd))
    exit()

if to_remove:
    cmd.append("-Rns")
    print(f"Uninstalling: {' '.join(to_remove)}")
    cmd.extend(to_remove)
    system(" ".join(cmd))
    exit()

if not to_install and not to_remove:
    print("System is in sync with desired state.")