#!/usr/bin/env python3
from os import system
from sys import exit
from os.path import exists
from subprocess import run, check_output, Popen, PIPE
import argparse

parser = argparse.ArgumentParser(
    prog='easypacman',
    description='Pacman wrapper with resonable syntax',
    # argument_default=[],
)


parser.add_argument('-i', '--install', nargs='*', help='Install package')
parser.add_argument('-I', '--install-interactive', action='store_true', help='Fuzzy search and install, <TAB> selects multiple')
parser.add_argument('-s', '--search', nargs='?', help='Search for package')
parser.add_argument('-r', '--uninstall', nargs='*', help='Uninstall package and dependencies')
parser.add_argument('-R', '--uninstall-interactive', action='store_true', help='Fuzzy search and uninstall, <TAB> selects multiple')

parser.add_argument('-u', '--upgrade', action='store_true', help='upgrade system')
parser.add_argument('--update', action='store_true', help='alias for upgrade')

parser.add_argument('--info', nargs='?', help='Show package info')

parser.add_argument('--list-installed', action='store_true', help='List installed packages')
parser.add_argument('--list-unneeded', action='store_true', help='List unneeded packages')
parser.add_argument('--list-aliens', action='store_true', help='List installed packages not in sync database')

parser.add_argument('--autoremove', action='store_true', help='Remove orphaned packages that are no longer needed')

parser.add_argument('--mark-explicit', nargs='*', help='Mark PACKAGE as explicitly installed')
parser.add_argument('--mark-dependency', nargs='*', help='Mark PACKAGE as dependency')

parser.add_argument('-y', '--assumeyes', action='store_true', help='Automatically answer yes to all questions')
parser.add_argument('-v', '--verbose', action='store_true', help='Show pacman command')

arguments, unknown = parser.parse_known_args()

cmd = []

if exists("/usr/bin/yay"):
    cmd.append("yay")
elif exists("/usr/bin/paru"):
    cmd.append("paru")
else:
    cmd.append("pacman")

if arguments.assumeyes:
    cmd.append("--noconfirm")

if arguments.install_interactive:
    # packages = check_output("pacman -Slq | fzf --multi --preview 'pacman -Si {1}'", shell=True, text=True)[:-1].split("\n")
    # print("Installing " + " ".join(packages))
    # cmd.insert(0, 'sudo')
    # cmd.extend(["-S", "--needed"])
    # cmd.extend(packages)
    system("pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S --needed")
    exit()

elif arguments.uninstall_interactive:
    system("pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns")
    exit()

elif arguments.install:
    cmd.insert(0, 'sudo')
    cmd.extend(["-S", "--needed"])
    cmd.extend(arguments.install)

elif arguments.search:
    cmd.append("-Ss")
    cmd.append(arguments.search)

elif arguments.uninstall:
    cmd.insert(0, 'sudo')
    cmd.append("-Rsn")
    cmd.extend(arguments.uninstall)

elif arguments.update or arguments.upgrade:
    cmd.insert(0, 'sudo')
    cmd.append("-Syu")

elif arguments.info:
    cmd.append("-Si")
    cmd.append(arguments.info)

elif arguments.list_installed:
    cmd.append("-Qeq")

elif arguments.list_unneeded:
    cmd.append("-Qdt")

elif arguments.list_aliens:
    cmd.append("-Qem")

elif arguments.autoremove:
    cmd.insert(0, 'sudo')
    cmd.append('pacman -Rsu $(pacman -Qdtq)')

elif arguments.mark_explicit:
    cmd.insert(0, 'sudo')
    cmd.extend(["-D", "--asexplicit"])
    cmd.extend(arguments.mark_explicit)

elif arguments.mark_dependency:
    cmd.insert(0, 'sudo')
    cmd.extend(["-D", "--asdeps"])
    cmd.extend(arguments.mark_dependency)

else:
    print("No argument given, running system upgrade")
    cmd.insert(0, 'sudo')
    cmd.extend(["-Syu", "--needed"])
    cmd.extend(unknown)

if arguments.verbose:
    print("-" * 20)
    print("Pacman command:")
    print(" ".join(cmd))
    print("-" * 20)

system(" ".join(cmd))

# alias paccup='sudo pacman -Sy >/dev/null && pacman -Qu' -s # check for updates
